#!/bin/bash

[ ! -f CA/root.key ] && [ ! -f CA/root.cert ] && {
    mkdir -p CA
    UUID=$(uuid -v 4)
    openssl genrsa -des3 -out CA/root.key 4096
    openssl req -x509 -new -nodes -key CA/root.key -sha256 -days 2000 \
        -out CA/root.crt -subj "/C=/ST=/L=/O=/OU=/CN=$UUID.rootca.logdb"
    openssl x509 -in CA/root.crt -text -noout
}


UUID=$(uuid -v 4)
openssl genrsa -out $UUID.$1.key 2048
openssl req -new -key $UUID.$1.key -out $UUID.$1.csr \
    -subj "/C=/ST=/L=/O=/OU=/CN=$UUID.$1.logdb"
openssl x509 -req -in $UUID.$1.csr -CA CA/root.crt -CAkey CA/root.key \
    -CAcreateserial -out $UUID.$1.crt -days 365 -sha256
openssl x509 -in $UUID.$1.crt -text -noout
